[core]
words = [
  "tomato",
  "potato",
]
log_file = "/var/log/twistd.log"
pid_file = "/var/run/twistd.pid"

[slack]
channel = "#random"
url = "https://hooks.slack.com/services/..."
username = "Twistd"
icon_emoji = ":bird:"

[twitter]
consumer_key = "********"
consumer_key_secret = "****************"
access_token = "********"
access_token_secret = "****************"
ignore_users = [
  "b4b4r07",
  #214516923, one of these
]
